Repository xmonad/xmonad-contrib, pull requests merged in 2020-12, with the labels that each got.

#427 Fix Documentation in X.H.FadeWindows
  XMonad/Hooks/FadeWindows.hs
Labels: 2.status: done, 6.topic: documentation, 9.needs: community feedback

#428 XMonad.Config.LXQt
  CHANGES.md
  XMonad/Config/LXQt.hs
  XMonad/Doc/Extending.hs
Labels: 0.kind: enhancement, 2.status: done, 9.needs: documentation

#434 Restarting status bars on restart
  CHANGES.md
  XMonad/Hooks/DynamicLog.hs
Labels: 2.status: done, 6.topic: hooks
