Repository xmonad/xmonad-contrib, pull requests merged in 2021-01, with the labels that each got.

#170 Only modify the last word during tab completion
  CHANGES.md
  XMonad/Prompt.hs
Labels: 0.kind: bug, 2.status: done, 6.topic: prompt, 9.needs: rebase, 9.needs: review, 9.needs: squash commits

#437 X.H.DynamicLog: Add ppTitleUnfocused
  CHANGES.md
  XMonad/Hooks/DynamicLog.hs
Labels: 0.kind: enhancement, 2.status: done, 6.topic: hooks

#441 Revise XDG handling
  CHANGES.md
  XMonad/Actions/Search.hs
  XMonad/Hooks/Script.hs
  XMonad/Prompt.hs
Labels: 0.kind: regression, 2.status: done

#442 X.Prompt: Correctly Update History with alwaysHighlight
  CHANGES.md
  XMonad/Prompt.hs
Labels: 0.kind: bug, 2.status: done, 6.topic: prompt, 9.needs: review

#444 Control.Exception.Extensible -> Control.Exception
  XMonad/Hooks/DebugEvents.hs
  XMonad/Prompt.hs
  XMonad/Prompt/AppendFile.hs
  XMonad/Prompt/Man.hs
  XMonad/Util/DebugWindow.hs
  XMonad/Util/NamedWindows.hs
  XMonad/Util/XSelection.hs
  xmonad-contrib.cabal
Labels: 2.status: done

#446 Generate CI with the haskell-ci utility.
  .github/workflows/haskell-ci.yml
  xmonad-contrib.cabal
Labels: 0.kind: enhancement

#406 X.H.ManageDocks: Init strut cache on demand if necessary
  CHANGES.md
  XMonad/Hooks/ManageDocks.hs
Labels: 0.kind: regression, 2.status: done, 6.topic: config

#447 Grab the Pointer in X.Prompt and X.A.TreeSelect
  CHANGES.md
  XMonad/Actions/TreeSelect.hs
  XMonad/Prompt.hs
Labels: 0.kind: bug, 3.skill X11, 6.topic: actions, 6.topic: prompt, 9.needs: CHANGES.md, 9.needs: community feedback

#440 X.L.NoBorders: Fix float handling on multihead setups
  CHANGES.md
  XMonad/Layout/NoBorders.hs
  tests/Main.hs
  tests/NoBorders.hs
  xmonad-contrib.cabal
Labels: 0.kind: regression, 2.status: done, 6.topic: layout

#453 Remove last occurences of non Data.Default defaults
  XMonad/Actions/Prefix.hs
  XMonad/Actions/TreeSelect.hs
  XMonad/Hooks/UrgencyHook.hs
  XMonad/Hooks/WallpaperSetter.hs
  XMonad/Layout/Fullscreen.hs
  XMonad/Util/SpawnNamedPipe.hs
Labels: 2.status: done, 6.topic: documentation

#397 X.U.PureX: Add focusWindow and focusNth
  CHANGES.md
  XMonad/Util/PureX.hs
Labels: 0.kind: enhancement, 6.topic: actions, 6.topic: config, 9.needs: review

#448 More loggers: A `maybe`-like combinator, and screen-specific loggers
  CHANGES.md
  XMonad/Util/Loggers.hs
Labels: 0.kind: enhancement, 9.needs: review
