Repository xmonad/xmonad-contrib, pull requests merged in 2021-03, with the labels that each got.

#459 X.Prompt: Correct tab completion handling
  CHANGES.md
  XMonad/Prompt.hs
Labels: 0.kind: bug, 2.status: done, 6.topic: prompt, 9.needs: review

#478 X.L.Magnifier: Update screenshot
  XMonad/Layout/Magnifier.hs
Labels: 2.status: done, 6.topic: documentation

#476 Add fullscreenSupportBorder
  CHANGES.md
  XMonad/Layout/Fullscreen.hs
Labels: 0.kind: enhancement, 2.status: done, 6.topic: layout, 9.needs: clean-up

#480 X.P.Pass: Update Documentation
  XMonad/Prompt/Pass.hs
Labels: 2.status: done, 6.topic: documentation, 9.needs: review

#450 Add Dynamic Icons based on the Windows inside a workspace
  CHANGES.md
  XMonad/Doc/Extending.hs
  XMonad/Hooks/DynamicIcons.hs
  xmonad-contrib.cabal
Labels: 0.kind: enhancement, 9.needs: review

#481 Extend PP with ppRename: nicer compose of WorkspaceNames, ClickableWorkspaces, …
  CHANGES.md
  XMonad/Actions/WorkspaceNames.hs
  XMonad/Hooks/DynamicLog.hs
  XMonad/Layout/IndependentScreens.hs
  XMonad/Util/ClickableWorkspaces.hs
Labels: 0.kind: enhancement, 0.kind: refactor

#487 Use time instead of old-time and old-locale
  XMonad/Actions/AfterDrag.hs
  XMonad/Util/Loggers.hs
  xmonad-contrib.cabal
Labels: 0.kind: refactor, 2.status: done, 6.topic: build, 9.needs: review

#479 X.A.TopicSpace: Deprecate internal history
  CHANGES.md
  XMonad/Actions/TopicSpace.hs
  XMonad/Hooks/WorkspaceHistory.hs
Labels: 0.kind: refactor, 2.status: done, 6.topic: actions, 9.needs: review
